#!/usr/bin/env php
<?php
use Symfony\Component\Console\Application;
use App\Console\Commands\GenerateKeyCommand;
use App\Console\Commands\ReloadCommand;
use App\Console\Commands\StartCommand;

require __DIR__ . '/vendor/autoload.php';

$application = new Application();

$application->add(new StartCommand());
$application->add(new GenerateKeyCommand());

$application->run();
